### ISSUE TITLE
Anti-Aliasing or faded transitions/edges

### ISSUE THREAD

**Issue by mybigfriendjo** [MMetze/DMHelper-Tracker#12]
**Nickname**
mybigfriendjo

**Is your feature request related to a problem? Please describe.**
While clearing FoW with the Circle tool the edges are anti-aliased or "soft" which looks smooth and there are no jagged edges.
The square and selection tool give a very hard edge. This is evident if you are drawing diagonally with them. This is sometimes very useful if i want precise control over what is shown and what isn't.
But it would be nice to be able to decide wheter i want a harsh edge or a soft one.

**Describe the solution you'd like**
A Checkbox that de-/activates Anti-Aliasing of "softening" of the Edges of the Brush/Selection Tool

**Describe alternatives you've considered**
Making all of them have one or the other. One yields precise control - the other looks better.

**Additional context**
None

**Comment by dm-helper** [comment]
Available with engineering pre-release 1.3.4
