### ISSUE TITLE
Known and Hidden Mechanics for (N)PCs

### ISSUE THREAD

**Issue by mybigfriendjo** [MMetze/DMHelper-Tracker#14]
**Nickname**
mybigfriendjo

**Is your feature request related to a problem? Please describe.**
Currently only monsters have the ability to be hidden/known on the Battle View. It would be awesome for immersion (NPC goes invisible) if the same could be applied to (N)PCs as well.

**Describe the solution you'd like**
Add the Known/Hidden Checkboxes and functionality to (N)PC Characters as well.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by dm-helper** [comment]
Character/NPC visibility/known is done, will be available starting with v1.3.4
