### ISSUE TITLE
Hotkey/Button for Cursor in BattleView

### ISSUE THREAD

**Issue by mybigfriendjo** [MMetze/DMHelper-Tracker#18]
**Nickname**
DrkNinja

**Is your feature request related to a problem? Please describe.**
Currently if you want to show an Arrow on the Players Window you need to switch back to the Main Window - open the Player Window Popup and there you can show an arrow via pressing space.
This would be more comfortable if that would work in the Battle View.

**Describe the solution you'd like**
A button and/or Hotkey within the Battle View that activates the Arrow directly from there.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by dm-helper** [comment]
Done in Ribbon UI, still needs polishing.
