### ISSUE TITLE
Add/Delete Wave 0

### ISSUE THREAD

**Issue by mybigfriendjo** [MMetze/DMHelper-Tracker#19]
**Nickname**
mybigfriendjo

**Describe the bug**
Wave 0 cannot be removed from the Encounter View in the Main Window which is more an optical thing than anything else.

However when the battle is opened, monsters from Wave 0 get automatically added to the initiative list.
For linear Encounters where there is only one possible Way to run it that is fine.
If the waves represent "rooms" of a dungeon that has multiple possible attack angles it might not necessarily be Wave 0 that comes into play first. So i have to leave Wave 0 empty and start with Wave 1 to not have Monsters added to the initiative List automatically.

**DMHelper version you're running**
1.3

**To Reproduce**
Add Encounter. Add Monsters to Wave 0. Start Battle.

**Expected behavior**
Not adding any Waves at the Beginning of a Battle or an option to deactivate the automatic adding of Wave 0.

**Screenshots**
![wave0](https://user-images.githubusercontent.com/7951032/63729397-5c76ff80-c867-11e9-95ab-f90834c3c1e2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
None

**Comment by turnercraig** [comment]
Remapped to a Feature Request as the existing functionality is by-design, even if that design is flawed.
