### ISSUE TITLE
FoW not working with 8-bit color-indexed pngs

### ISSUE THREAD

**Issue by mybigfriendjo** [MMetze/DMHelper-Tracker#20]
**Nickname**
ColonelPanic

**Describe the bug**
FoW does not work with certain png files. In Map View they show only a black image. In Battle View they show no FoW

**DMHelper version you're running**
1.3.2

**To Reproduce**
Load up an 8-bit color-indexed png as map (https://cdn.discordapp.com/attachments/599266810369540142/614780672602669056/SPOILER_Dripping_Caves.png) and use FoW Tools. Then open Map View and/or Battle View.

**Expected behavior**
FoW being applied to the image in Map View and Battle View.

**Screenshots**
https://cdn.discordapp.com/attachments/609515792169435137/614774486469836810/unknown.png
https://cdn.discordapp.com/attachments/609515792169435137/614775425293615104/unknown.png

**Desktop (please complete the following information):**
 - OS: Win10 and OSX

**Additional context**
None

**Comment by mybigfriendjo** [comment]
Yes, however the Fix was not yet released with a new Version.
Usually Issues are kept open until the fix is actually released.
In either case DMHelper can close this issue whenever he deems it "resolved".

**Comment by turnercraig** [comment]
Will be available in Engineering Prerelease 1.3.3
