### ISSUE TITLE
[FEAT REQ] Encounter Grouping (temporary)

### ISSUE THREAD

**Issue by DrkNinja** [MMetze/DMHelper-Tracker#26]
**Discord User:**
๖DrkNinja

**Is your feature request related to a problem? Please describe.**
Sorting through a massive amount of possible encounters.

**Describe the solution you'd like**
Add a grouping/folder system for encounters for further organization

**Describe alternatives you've considered**
N/A

**Additional context**
Would be irrelevant once the Layers system is introduced, Would only serve a purpose until v2.0 was released with Layers integrated.

**Comment by dm-helper** [comment]
Dynamic campaign tree resolves this
