### ISSUE TITLE
'Dead Combatants' are Not Being Removed from Battle Encounters

### ISSUE THREAD

**Issue by DrkNinja** [MMetze/DMHelper-Tracker#27]
**Discord User:**
๖DrkNinja

**Describe the bug**
Damage dealt via context menu on an active initiative tile causes the entity to not show as dead and be removed from the initiative or the token from the battle encounter.

**DMHelper version you're running**
DMH v1.3.2

**To Reproduce**
1. Set up an initiative in an open battle encounter
2. While on a PCs turn, right click a Mob/NPC, and select damage
3. If the damage is more than or equal to it's total HP the entity will fail to register as a 'dead combatant' and remains

**Expected behavior**
Once a PC/NPC/Mob's HP reaches 0 by any means, the entity should be labeled a 'dead combatant' by DMH and eliminate them from initiative and the battle encounter if 'Show dead combatants' is unticked.

**Screenshots**
N/A

**Desktop (please complete the following information):**
Windows 10 Pro

**Additional context**
N/A

**Comment by turnercraig** [comment]
Fixed, tagged to the (renamed) 1.3 milestone, will be available in Engineering Prerelease 1.3.3

**Comment by dm-helper** [comment]
Test comment...

**Comment by DrkNinja** [comment]
Same issue occurs with the spell effects damage, except it doesn't bug the npc/mob permanently. Quickly changing the hp to 1 then 0 fixes the problem.

**Comment by dm-helper** [comment]
Fixed again, moved to Engineering Prerelease 1.3.4
