### ISSUE TITLE
Flexible campaign structure

### ISSUE THREAD

**Issue by dm-helper** [MMetze/DMHelper-Tracker#30]
**Discord User:**
DMHelper (Dev) / pibebtol 

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
A flexible campaign tree where campaign items such as 'Setting', 'Adventure', 'Map', 'Encounter', etc. can be placed under any campaign items defining a campaign tree however each DM/GM sees fit.

**Describe alternatives you've considered**
N/A

**Additional context**
Being able to add descriptions or context to each campaign item, which may be published to the players if the need arised.

**Comment by mybigfriendjo** [comment]
With the rework of the Menu Structure pibebtol suggested adding comment functionality to each item (maybe every item can have a comment-subitem)
Also a feature to make the comments or part of them publishable would add flexibility.
