### ISSUE TITLE
Publish Button Not Scaling to UI at Higher Res

### ISSUE THREAD

**Issue by DrkNinja** [MMetze/DMHelper-Tracker#34]
**Discord User:**
๖DrkNinja

**Describe the bug:**
Publish button is too big for it's britches

**DMHelper version:**
1.3.3

**To Reproduce:**
Maximize DMH window on a high res monitor

**Expected behavior:**
Publish button to match image size.

**Screenshots:**
![DMHelper 08-30-19  12 12 12AM](https://user-images.githubusercontent.com/1700660/64057389-3bb1f100-cb6a-11e9-83de-3a1d3f91800d.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context:**
None

**Comment by dm-helper** [comment]
Fixed, tagged to the 1.3 milestone, will be available in Engineering Prerelease 1.3.4
