### ISSUE TITLE
Monster Tokens Moving On Their Own

### ISSUE THREAD

**Issue by DrkNinja** [MMetze/DMHelper-Tracker#43]
**Discord User:**
๖DrkNinja

**Describe the bug:**
I've only had it happen 3 times and I can't tell you how or why it happened but I was trying to move a token, for some reason it made me move all of them, so I put them back. Then I deactivated a mob and moved just one and I noticed that I was missing a mob. The first time I thought it had been removed by accident but it was still showing up in Initiative, I later found out it had moved to the top left corner of the map and since I was zoomed in I couldn't see it. Every time it's moved to the same corner.

**DMHelper version:**
1.3.4

**To Reproduce:**
N/A

**Expected behavior:**
N/A

**Screenshots:**

**Desktop (please complete the following information):**
Windows 10

**Additional context:**
When first entering an encounter and sometimes when a monster is activated in the initiative I can't move one token, it makes me move all of them.

**Comment by dm-helper** [comment]
This happened due to using the drag rubber band for zoom which then "secretly" selected all visible monsters. This has been fixed. A future improvement to properly visualize all selected creatures is a separate topic in the backlog.
