### ISSUE TITLE
Plus Buttons for Tree UI

### ISSUE THREAD

**Issue by DrkNinja** [MMetze/DMHelper-Tracker#56]
**Discord User:**
If you're creating this for someone else on the discord, please state the nickname

**Is your feature request related to a problem? Please describe.**
Intuitiveness 

**Describe the solution you'd like**
"Plus buttons next to Party, Adventures, Encounter, Map, NPC, Item would be useful. I love right clicking, but that's not completely intuitive"

**Describe alternatives you've considered**
N/A

**Additional context**
May be apart of Flexible Campaign Tree.

**Comment by dm-helper** [comment]
Resolved with the Ribbon - there are dedicated buttons to add items
