### ISSUE TITLE
DM Screen Scroll Bar

### ISSUE THREAD

**Issue by DrkNinja** [MMetze/DMHelper-Tracker#58]
**Discord User:**
Mad Milliner

**Is your feature request related to a problem? Please describe.**
Information not visible due to window sizing

**Describe the solution you'd like**
Add a scroll bar on the DM Screen 

**Describe alternatives you've considered**
N/A

**Additional context**
May be irrelevant after Ribbon UI, if implemented

**Comment by dm-helper** [comment]
Note: Need to check whether or not this is still relevant in the new Ribbon UI
