### ISSUE TITLE
Mob HP Generation Removed

### ISSUE THREAD

**Issue by DrkNinja** [MMetze/DMHelper-Tracker#60]
**Discord User:**
Cyrano

**Describe the bug:**
No longer allowed to edit mobs' HP before being added to an encounter

**DMHelper version:**
1.6

**To Reproduce:**
1. Add Monster to encounter
2. Dialog box appear missing HP generation input field

**Expected behavior:**
Revert to old Mob dialog box

**Screenshots:**
https://media.discordapp.net/attachments/609515792169435137/679819162121666586/unknown.png

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context:**

> [5:39 PM] DMHelper: The next one will be back with v1.7. My bad that the wrong one survived!

**Comment by dm-helper** [comment]
Adding the previous CombatantDialog (from EncounterBattle) to BattleFrame
