### ISSUE TITLE
Condition Labels in Combat

### ISSUE THREAD

**Issue by DrkNinja** [MMetze/DMHelper-Tracker#61]
**Discord User:**
๖DrkNinja#7015

**Is your feature request related to a problem? Please describe.**
Unclear condition status' during combat

**Describe the solution you'd like**
A label that appears above the mobs, maybe different color variations, and single letters 

**Describe alternatives you've considered**
A label that appears when targeting a mob

**Additional context**
High priority

**Comment by dm-helper** [comment]
@DrkNinja is this a duplicate of https://github.com/MMetze/DMHelper-Tracker/issues/81 ? If yes, please delete one of them...

**Comment by dm-helper** [comment]
Closed as a duplicate of #81
