### ISSUE TITLE
Edit Button witout function

### ISSUE THREAD

**Issue by MMetze** [MMetze/DMHelper-Tracker#63]
**Discord User:**
@Ambient Nomad#5143

**Describe the bug:**
There is an edit button without function

**DMHelper version:**
1.6

**To Reproduce:**
1. Start DM Helper
2. Click Edit

**Expected behavior:**
Either a menu appears, or the button should be disabled / invisible

**Desktop (please complete the following information):**
 - OS: Win10x64

**Comment by MMetze** [comment]
The button is context sensitive, but does not show it.

**Comment by dm-helper** [comment]
Gone - there is no more Edit menu entry in the Ribbon UI. 

For reference, this was actually "by design" - the Edit menu was where the "Undo" and "Redo" actions were in the previous verisons, which were only visible when you were looking at a map
