### ISSUE TITLE
Custom Monsters Options from 'Add Monster' Dialog

### ISSUE THREAD

**Issue by DrkNinja** [MMetze/DMHelper-Tracker#69]
**Discord User:**
xXAquaNightXx

**Is your feature request related to a problem? Please describe.**
Quickly adding monsters to the initiative on the fly

**Describe the solution you'd like**
Options in the 'Add Monster' Dialog box to create a custom monster. Options including  name, AC, HP, image, add to initiative, and save into bestiary

**Describe alternatives you've considered**
N/A

**Additional context**
https://cdn.discordapp.com/attachments/619284191665717278/680436244047855661/add_dialogue.PNG

**Comment by dm-helper** [comment]
The wrong dialog was still active in v1.6, there is a much better one available which has been reintroduced for the next version.
