### ISSUE TITLE
Added Characters Not Displaying Properly

### ISSUE THREAD

**Issue by DrkNinja** [MMetze/DMHelper-Tracker#71]
**Discord User:**
MadMilliner

**Describe the bug:**
Characters do not always display immediately when adding them, requires a restart to view.

**DMHelper version:**
1.6

**To Reproduce:**
N/A

**Expected behavior:**
N/A

**Screenshots:**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 
 - Version 10.14.6

**Additional context:**

> [2:38 PM] DMHelper: Ah ok, that last one is a bug I've never focused on enough to fix. Obviously not ok.

**Comment by dm-helper** [comment]
Fixed - clicking on enable/disable character would make the campaign tree no longer properly get updates (1-line fix!)
