### ISSUE TITLE
Import XML Files From Lion's Den

### ISSUE THREAD

**Issue by DrkNinja** [MMetze/DMHelper-Tracker#79]
**Discord User:**
xXAquaNightXx

**Describe the feature request you'd like:**
Add the ability to import XML files/format that are also used by Lion's Den

**Is your feature request related to a problem? Please describe:**
N/A

**Describe alternatives you've considered:**
N/A

**Additional context:**
2/21/20 [10:30 AM] xXAquaNightXx Add the ability to import xml files/format that are also used by Lion's Den that app has complete bestiaries etc. available (from third party sources) that would make having a complete bestiary easier.

**Comment by mybigfriendjo** [comment]
There is a converter for this already - it can be expanded on to whatever degree needed/wanted. Atm it is more about integrating certain values into DMHelper that currently are just flatout missing otherwise.
