### ISSUE TITLE
Hotkeys & Hotkey Mapping

### ISSUE THREAD

**Issue by DrkNinja** [MMetze/DMHelper-Tracker#83]
**Discord User:**
Klokwurk & DrkNinja

**Describe the feature request you'd like:**
Hotkeys for tools such as FoW brush size (Key+Scrollwheel), zoom, scrolling, whether your removing or replacing FoW, etc.

**Is your feature request related to a problem? Please describe:**
N/A

**Describe alternatives you've considered:**
N/A

**Additional context:**
N/A

**Comment by dm-helper** [comment]
Duplicate of Issue #106
