### ISSUE TITLE
Cursor Only Changes With 32-bit Images

### ISSUE THREAD

**Issue by DrkNinja** [MMetze/DMHelper-Tracker#90]
**Discord User:**
๖DrkNinja

**Ticket Transcript**
[Link](https://tickettool.xyz/direct?url=https://cdn.discordapp.com/attachments/689247473453105156/694903425439367240/transcript-bug-cursor-supports-only-32-bit-images.html)

**Describe the bug:**
Cursor does not support images that aren't 32 bit images

**DMHelper version:**
1.7.9

**To Reproduce:**

**Expected behavior:**
Any image should be available to be used as a cursor

**Screenshots:**

**Desktop (please complete the following information):**
 - OS: Window 10

**Additional context:**

**Comment by dm-helper** [comment]
Confirmed implemented in 2.0
