### ISSUE TITLE
Zoom Data Resets On Window Movement

### ISSUE THREAD

**Issue by DrkNinja** [MMetze/DMHelper-Tracker#94]
**Discord User:**
Brian

**Ticket Transcript **
[Link To Transcript](https://tickettool.xyz/direct?url=https://cdn.discordapp.com/attachments/689247473453105156/694979776489848936/transcript-bug-zoom-reset-on-window-resize.html)

**Describe the bug:**
Zoom in/out data resets on window movement.

**DMHelper version:**
1.7.8

**Is there an expected behavior? If yes, what is the expected behavior.**
Zoom data remains no matter what.

**Comment by dm-helper** [comment]
Fixed for static images, not yet fully for animated
